"""Task 128: formal deterministic reasoning-run replay.

Replay means: re-derive the deterministic reasoning run from recorded
inputs and prove it matches the recorded original. Replay is strictly
read-only -- it recomposes the run and its audit from current state
without writing, so the original run is never mutated. Any divergence
(input drift, stage reorder, source change, consistency loss) is
reported explicitly in the replay result, never silently accepted.

The caller supplies the recorded original: its execution result plus
the input snapshot that produced it. The snapshot's full fingerprint is
verified first so a tampered recording cannot replay as genuine. Input
comparison then covers the exogenous projection (session, user input,
observations, entities): derived collections are legitimately
regenerated by every execution, so the recomposed run stages and
consistency audit -- not regenerated identities -- bind derived state.

The existing GET /sessions/{id}/replay step log is untouched.
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy.orm import Session

from rop.schemas.reasoning_run_replay import ReasoningRunReplayRead
from rop.services.reasoning_run import ReasoningRunService
from rop.services.reasoning_run_consistency import (
    ReasoningRunConsistencyService,
)
from rop.services.reasoning_run_fingerprint import (
    compute_snapshot_fingerprint,
    verify_snapshot_fingerprint,
)
from rop.services.reasoning_run_idempotency import derive_run_identity
from rop.services.reasoning_run_input_snapshot import (
    ReasoningRunInputSnapshotService,
)

REASONING_RUN_REPLAY_SOURCE_TASK_128 = "REASONING_RUN_REPLAY_TASK_128"

#: Snapshot collections the execution engine never rewrites once
#: present. Replay input comparison covers exactly these: derived
#: collections (missing information, templates, candidates, evidence)
#: are legitimately regenerated by every execution with fresh
#: identities, so they cannot distinguish replay from drift. The
#: recomposed run stages and consistency audit bind derived state.
EXOGENOUS_SNAPSHOT_FIELDS = (
    "session_id",
    "user_input",
    "observations",
    "entities",
)


def exogenous_projection(snapshot: dict[str, Any]) -> dict[str, Any]:
    """Project a snapshot onto its exogenous (engine-external) inputs."""
    return {field: snapshot.get(field) for field in EXOGENOUS_SNAPSHOT_FIELDS}


class ReasoningRunReplayContractError(Exception):
    """Task 128: replay could not be evaluated or trusted."""

    def __init__(self, invariant: str, detail: str) -> None:
        self.invariant = invariant
        super().__init__(f"[{invariant}] {detail}")


class ReasoningRunReplayService:
    """Read-only replay evaluator over recorded deterministic runs."""

    def __init__(
        self,
        snapshot_service: ReasoningRunInputSnapshotService | None = None,
        reasoning_run_service: ReasoningRunService | None = None,
        reasoning_run_consistency_service: ReasoningRunConsistencyService | None = None,
    ) -> None:
        self.snapshot_service = snapshot_service or ReasoningRunInputSnapshotService()
        self.reasoning_run_service = reasoning_run_service or ReasoningRunService()
        self.reasoning_run_consistency_service = (
            reasoning_run_consistency_service or ReasoningRunConsistencyService()
        )

    def replay(
        self,
        db: Session,
        session_id: UUID,
        *,
        original_result: dict[str, Any],
        original_snapshot: dict[str, Any],
    ) -> dict[str, Any]:
        """Replay a recorded run and report every divergence."""
        if not isinstance(original_result, dict) or not isinstance(
            original_snapshot, dict
        ):
            raise ReasoningRunReplayContractError(
                "RECORD_INVALID",
                "original result and snapshot mappings are required",
            )
        original_fingerprint = original_result.get("input_fingerprint")
        if not isinstance(original_fingerprint, str):
            raise ReasoningRunReplayContractError(
                "RECORD_INVALID",
                "original result carries no input fingerprint",
            )

        # The recording itself must be genuine before replay means anything.
        record_issues = verify_snapshot_fingerprint(
            original_snapshot, original_fingerprint
        )
        if record_issues:
            raise ReasoningRunReplayContractError(
                "RECORD_TAMPERED",
                "recorded snapshot does not match its fingerprint: "
                + "; ".join(record_issues),
            )

        current_snapshot = self.snapshot_service.build_snapshot(db, session_id)
        replay_fingerprint = compute_snapshot_fingerprint(current_snapshot)
        divergences: list[str] = []
        # Replay input identity is exogenous: the engine legitimately
        # regenerates derived collections on every execution, so only
        # engine-external inputs distinguish drift from defined behavior.
        if exogenous_projection(current_snapshot) != exogenous_projection(
            original_snapshot
        ):
            divergences.append("INPUT_CHANGED_SINCE_ORIGINAL")

        try:
            run = self.reasoning_run_service.build_for_session(db, session_id)
            audit = self.reasoning_run_consistency_service.build_for_session(
                db, session_id
            )
        except Exception as exc:
            raise ReasoningRunReplayContractError(
                "REPLAY_BUILD_FAILED",
                "replay recomposition failed: " + type(exc).__name__,
            ) from exc

        stage_comparison = self._compare_stages(original_result, run, divergences)
        if audit.get("run_consistent") is not True:
            divergences.append("REPLAY_RUN_INCONSISTENT")

        replay_consistent = not divergences
        input_match = "INPUT_CHANGED_SINCE_ORIGINAL" not in divergences
        result = {
            "original_run_identity": derive_run_identity(
                session_id, original_fingerprint
            ),
            "original_input_fingerprint": original_fingerprint,
            "replay_input_fingerprint": replay_fingerprint,
            "input_match": input_match,
            "stage_comparison": stage_comparison,
            "divergences": sorted(set(divergences)),
            "replay_consistent": replay_consistent,
            "replay_source": REASONING_RUN_REPLAY_SOURCE_TASK_128,
        }
        return ReasoningRunReplayRead.model_validate(result).model_dump()

    @staticmethod
    def _compare_stages(
        original_result: dict[str, Any],
        run: dict[str, Any],
        divergences: list[str],
    ) -> list[dict[str, Any]]:
        """Compare recorded Task 042 run stages against recomposed ones.

        The original execution result embeds its ``reasoning_run`` with
        the exact Task 042 stage list; replay recomposes the same view
        read-only. Binding is by stage identity, order, and source --
        never blind flag trust.
        """
        comparison: list[dict[str, Any]] = []
        recorded_run = original_result.get("reasoning_run")
        if not isinstance(recorded_run, dict):
            divergences.append("ORIGINAL_RUN_MISSING")
            return comparison
        recorded_stages = recorded_run.get("stages")
        if not isinstance(recorded_stages, list):
            divergences.append("ORIGINAL_STAGES_MISSING")
            return comparison
        replayed_stages = run.get("stages")
        if not isinstance(replayed_stages, list):
            divergences.append("REPLAY_STAGES_MISSING")
            return comparison
        if len(recorded_stages) != len(replayed_stages):
            divergences.append("STAGE_COUNT_DIVERGED")
        for position, (recorded, replayed) in enumerate(
            zip(recorded_stages, replayed_stages, strict=False)
        ):
            if not isinstance(recorded, dict) or not isinstance(replayed, dict):
                divergences.append(f"STAGE_MALFORMED:{position}")
                continue
            stage_id = str(recorded.get("stage_id"))
            expected_source = str(recorded.get("stage_source"))
            replayed_source = str(replayed.get("stage_source"))
            match = (
                str(replayed.get("stage_id")) == stage_id
                and replayed_source == expected_source
                and replayed.get("stage_order") == recorded.get("stage_order")
            )
            if not match:
                divergences.append(f"STAGE_DIVERGED:{stage_id}")
            comparison.append(
                {
                    "stage_id": stage_id,
                    "stage_order": int(recorded.get("stage_order", position)),
                    "expected_source": expected_source,
                    "replayed_source": replayed_source,
                    "match": bool(match),
                }
            )
        return comparison
